if(USE_NATIVE_TU_PARSER) {

setClass( 'GCC::Node::abs_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::addr_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::array_ref' , contains =  "OperandNode" )
 setClass( 'GCC::Node::array_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::arrow_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::baselink' , contains =  "GCCNode" )
 setClass( 'GCC::Node::bind_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::binfo' , contains =  "GCCNode" )
 setClass( 'GCC::Node::bit_and_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::bit_field_ref' , contains =  "GCCNode" )
 setClass( 'GCC::Node::bit_ior_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::bit_not_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::bit_xor_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::boolean_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::break_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::call_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::case_label' , contains =  "OperandNode" )
 setClass( 'GCC::Node::case_label_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::cast_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::complex_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::complex_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::component_ref' , contains =  "OperandNode" )
 setClass( 'GCC::Node::compound_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::compound_stmt' , contains =  "OperandNode" )
 setClass( 'GCC::Node::cond_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::const_cast_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::const_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::constructor' , contains =  "GCCNode" )
 setClass( 'GCC::Node::continue_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::convert_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::ctor_initializer' , contains =  "GCCNode" )
 setClass( 'GCC::Node::ctor_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::decl_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::decl_stmt' , contains =  "OperandNode" )
 setClass( 'GCC::Node::dl_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::do_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::dotstar_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::enumeral_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::eq_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::error_mark' , contains =  "GCCNode" )
 setClass( 'GCC::Node::expr_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::field_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::file_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::fix_trunc_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::float_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::for_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::function_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::function_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::ge_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::goto_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::goto_stmt' , contains =  "OperandNode" )
 setClass( 'GCC::Node::gt_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::handler' , contains =  "GCCNode" )
 setClass( 'GCC::Node::identifier_node' , contains =  "GCCNode" )
 setClass( 'GCC::Node::if_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::imagpart_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::indirect_ref' , contains =  "OperandNode" )
 setClass( 'GCC::Node::init_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::integer_cst' , contains =  "GCCNode" )
 setClass( 'GCC::Node::integer_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::label_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::label_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::label_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::lang_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::le_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::lshift_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::lt_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::max_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::member_ref' , contains =  "GCCNode" )
 setClass( 'GCC::Node::method_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::min_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::minus_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::modify_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::modop_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::mult_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::namespace_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::ne_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::negate_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::non_lvalue_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::nop_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::nw_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::obj_type_ref' , contains =  "GCCNode" )
 setClass( 'GCC::Node::overload' , contains =  "GCCNode" )
 setClass( 'GCC::Node::parm_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::plus_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::pointer_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::postdecrement_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::postincrement_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::predecrement_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::preincrement_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::rdiv_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::real_cst' , contains =  "GCCNode" )
 setClass( 'GCC::Node::realpart_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::real_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::record_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::reference_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::reinterpret_cast_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::result_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::return_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::return_stmt' , contains =  "OperandNode" )
 setClass( 'GCC::Node::rshift_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::save_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::scope_ref' , contains =  "GCCNode" )
 setClass( 'GCC::Node::scope_stmt' , contains =  "OperandNode" )
 setClass( 'GCC::Node::sizeof_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::statement_list' , contains =  "GCCListNode" )
 setClass( 'GCC::Node::static_cast_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::stmt_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::string_cst' , contains =  "GCCNode" )
 setClass( 'GCC::Node::switch_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::switch_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::target_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::template_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::template_id_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::template_parm_index' , contains =  "GCCNode" )
 setClass( 'GCC::Node::template_type_parm' , contains =  "GCCNode" )
 setClass( 'GCC::Node::throw_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::translation_unit_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::tree_list' , contains =  "GCCNode" )
 setClass( 'GCC::Node::tree_vec' , contains =  "GCCListNode" )
 setClass( 'GCC::Node::trunc_div_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::trunc_mod_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::truth_and_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::truth_andif_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::truth_not_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::truth_or_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::truth_orif_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::try_block' , contains =  "GCCNode" )
 setClass( 'GCC::Node::try_catch_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::try_finally' , contains =  "OperandNode" )
 setClass( 'GCC::Node::type_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::typename_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::union_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::var_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::vector_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::void_type' , contains =  "GCCNode" )
 setClass( 'GCC::Node::while_stmt' , contains =  "GCCNode" )
 setClass( 'GCC::Node::exact_div_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::floor_div_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::floor_mod_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::ceil_div_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::ceil_mod_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::round_div_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::round_mod_expr' , contains =  "OperandNode" )
 setClass( 'GCC::Node::aggr_init_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::using_decl' , contains =  "GCCNode" )
 setClass( 'GCC::Node::asm_expr' , contains =  "GCCNode" )
 setClass( 'GCC::Node::tag_defn' , contains =  "GCCNode" )
 setClass( 'GCC::Node::offset_type' , contains =  "GCCNode" )
setMethod('getNextNode', 'GCC::Node::const_decl' , function(node) node[['chan']])
setMethod('getNextNode', 'GCC::Node::field_decl' , function(node) node[['chan']])
setMethod('getNextNode', 'GCC::Node::function_decl' , function(node) node[['chan']])
setMethod('getNextNode', 'GCC::Node::label_decl' , function(node) node[['chan']])
setMethod('getNextNode', 'GCC::Node::namespace_decl' , function(node) node[['chan']])
setMethod('getNextNode', 'GCC::Node::overload' , function(node) node[['chan']])
setMethod('getNextNode', 'GCC::Node::parm_decl' , function(node) node[['chan']])
setMethod('getNextNode', 'GCC::Node::template_decl' , function(node) node[['chan']])
setMethod('getNextNode', 'GCC::Node::tree_list' , function(node) node[['chan']])
setMethod('getNextNode', 'GCC::Node::type_decl' , function(node) node[['chan']])
setMethod('getNextNode', 'GCC::Node::var_decl' , function(node) node[['chan']])
setMethod('getNodeSource', 'GCC::Node::const_decl' , function(node) node[['source']])
setMethod('getNodeSource', 'GCC::Node::field_decl' , function(node) node[['source']])
setMethod('getNodeSource', 'GCC::Node::function_decl' , function(node) node[['source']])
setMethod('getNodeSource', 'GCC::Node::label_decl' , function(node) node[['source']])
setMethod('getNodeSource', 'GCC::Node::namespace_decl' , function(node) node[['source']])
setMethod('getNodeSource', 'GCC::Node::parm_decl' , function(node) node[['source']])
setMethod('getNodeSource', 'GCC::Node::result_decl' , function(node) node[['source']])
setMethod('getNodeSource', 'GCC::Node::template_decl' , function(node) node[['source']])
setMethod('getNodeSource', 'GCC::Node::translation_unit_decl' , function(node) node[['source']])
setMethod('getNodeSource', 'GCC::Node::type_decl' , function(node) node[['source']])
setMethod('getNodeSource', 'GCC::Node::var_decl' , function(node) node[['source']])

}
