index.html:

VERSION_INFO=../VersionInfo
TARGET_DIR=www.omegahat.org:OmegaWeb/RGCCTranslationUnit

include $(OMEGA_HOME)/Config/GNUmakefile.SWebPackageConfig

include $(OMEGA_HOME)/Config/GNUmakefile.SWebPackageRules

XML_DOCS=derivedClasses outargs intro overview registration
XML_FILES=$(XML_DOCS:%=../inst/doc/%.xml)

